---
- hosts: all
  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - vim
        - neovim

    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - file: path=~/.config/nvim/{{ item }} state=directory recurse=Yes
      with_items:
        - autoload

    - file: src={{ curdir }}/files/vimrc dest=~/.config/nvim/init.vim state=link

    - get_url:
        dest: ~/.config/nvim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # - git:
    #     repo: 'https://github.com/VundleVim/Vundle.vim.git'
    #     dest: ~/.vim/bundle/Vundle.vim
    #     version: v0.10.2

    - file: path=~/.vim/spell state=directory

    # - command: nvim -i NONE -c PlugUpdate -c quitall
    # FIXME: compile https://github.com/Shougo/vimproc.vim
